# Generated by Django 3.0.2 on 2020-01-28 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0002_auto_20200124_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='hostUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
